### ISSUE TITLE
Error opening File

### ISSUE THREAD

**Issue by brandon-a** [brandon-a/CIS-22C-Group-Project#2]
inFile.open("..\ResourceFile\USDA_data_small.txt");

Opening the file as shown above produces an error. How would we go about opening the file that is in the ResourceFile folder?

**Comment by theorangepotato** [comment]
The problem is the backslashes (). They are really only used in the Windows file system, most other OSes (Unix-like) use the slash (/), as does the compiler. Also, a backslash in a string literal needs to be cancelled out by another backslash (\).

But anyway, the answer is to write:
inFile.open("../ResourceFile/USDA_data_small.txt");

This seemed to work for me. I'm closing the issue for now, however, reopen it if it doesn't work for you.
