### ISSUE TITLE
We should not be able to have duplicate unique keys.

### ISSUE THREAD

**Issue by brandon-a** [brandon-a/CIS-22C-Group-Project#29]
Do not allow duplicate unique keys to be entered. Duplicate secondary keys are acceptable.

**Comment by theorangepotato** [comment]
I implemented a test in Hash and used that for all of the add functions. Just as I write this I realize we may (or really may not) want to put this check in the file in as well, but if we assume all good data, then we don't really have to. If you agree that we don't need to implement this, close this issue, otherwise add it and then close.

**Comment by brandon-a** [comment]
I think we don't need to implement it, do you think that's fine or should I add it anyway?

**Comment by theorangepotato** [comment]
I feel like it's just an unnecessary check. If you wanna be really safe, put it in, otherwise, I'm fine with leaving it out.

**Comment by Jasko-A** [comment]
I agree with Austin, let's leave it out. If she mentions anything well add
it before we turn it in on friday.

**Comment by brandon-a** [comment]
Ok sounds good, I'll close this then.
